# FROM python:3.10-slim
# WORKDIR /app
# COPY requirements.txt .
# RUN  pip install --upgrade pip
# RUN pip install -r requirements.txt
# COPY . .
# #CMD [ "nohup", "python3", "app.py", "&" ]
# CMD [ "python3", "app.py" ]
# JUST :) 